# Generated by Django 3.0.4 on 2020-03-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200320_2314'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_name_a7d948_idx',
        ),
    ]
